allowBuilds:
  "@parcel/watcher": false
overrides:
  "@scala-js/vite-plugin-scalajs>vite": "catalog:"
  "esbuild": "-"
catalog:
  vite: ^8.2.2
patchedDependencies:
  '@scala-js/vite-plugin-scalajs': patches/@scala-js__vite-plugin-scalajs.patch
